platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!

def kotlin_pods
    pod 'shared', :path => "../shared"
    pod 'core_ui', :path => "../core-ui"
end

target 'iosApp' do
    use_frameworks!
    kotlin_pods
end